export const mockData = [
    {
      // botImage: "/images/robot.png",
      chargingStatus: "",
      PowerStatus: "/images/Eightypercentage.png",
      percentage:100,
      name: "Emily Garcia",
      place: "New York, USA",
      id:1364,
    },
    {
      botImage: "/images/robot.png",
      chargingStatus: "",
      PowerStatus: "/images/Eightypercentage.png",
      name: "Jacob Patel",
      place: "London, UK",
      percentage:"20",
      id:1324,
    },
    {
      botImage: "/images/robot.png",
      chargingStatus: "/images/spark-green.png",
      PowerStatus: "/images/tenpercentage.png",
      name: "Samantha Lee",
      place: "Sydney, Australia",
      percentage:"10",
      id:1024,
    },
    {
      botImage: "/images/robot.png",
      chargingStatus: "/images/spark-green.png",
      PowerStatus: "/images/tenpercentage.png",
      name: "Joshua Kim",
      place: "Tokyo, Japan ",
      percentage:"10",
      id:1304,
    },
    {
      botImage: "/images/robot.png",
      chargingStatus: "/images/spark-green.png",
      PowerStatus: "/images/charging.png",
      name: "Olivia Singh",
      place: "Paris, France",
      percentage:"100",
      id:1320,
        },
  ];