import axios from "../utils/axios";

export const addRobot = (data) => {
  // Return the promise generated by the axios.post call
  return new Promise((resolve, reject) => {
    axios.post('/owner/connect-robot', { robot_uuid: data })
      .then(response => {
        // Handle the response data if needed
        resolve(response.data);
      })
      .catch(error => {
        // Handle the error if needed
        reject(error);
      });
  });
};
